language: python
env:
  - DJANGO="django==1.3.5"
  - DJANGO="django==1.4.3"
  - DJANGO=https://github.com/django/django/zipball/master
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
    - pip install -q $DJANGO --use-mirrors
    - pip install -q pillow --use-mirrors
    - pip install -q -r requirements.txt --use-mirrors
    - python setup.py develop
script: tests/test.sh
